# Base configs
baseurl: "https://travel.hackernextdoor.club"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-142036827-1"

# UI configs
title: "A Hacker Next Door Travel Blog"
subtitle: "ì‹ ì… ëª¨ì˜í•´ì»¤ì˜ ì—¬í–‰ ë¸”ë¡œê·¸ ì…ë‹ˆë‹¤."
author: "Ram Patra"
header:
 title: "A Hacker Next Door Travel Blog"
 subtitle: "by JayCho"
footer:
 name: "ì•ˆë…•í•˜ì„¸ìš”ğŸ‘‹"
 bio: "ì‹ ì… ëª¨ì˜í•´ì»¤ì¸ JayChoì…ë‹ˆë‹¤[[Github]](https://github.com/Taylorcho123){:target="_blank"}.ğŸ™‚ ì—¬ê¸°ëŠ” ì œ ì—¬í–‰ì‚¬ì§„ë“¤ì„ ì˜¬ë ¤ë‘ëŠ” ê³³ì…ë‹ˆë‹¤."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/eunjae.cho.146"
  twitter: "https://twitter.com/m4thm3d14"
  github: "https://github.com/Taylorcho123"
